sudo: false
language: go

before_install:
  - go get -t -v ./...
  - go get github.com/mattn/goveralls
script:
  - go test -coverprofile=sdc.coverprofile
  - goveralls -coverprofile=sdc.coverprofile -service=travis-ci
